title: Drivers
author: Jenny Ames
email: jennifer.ames@intersystems.com
description: > # this means to ignore newlines until "baseurl:"
  Download drivers to support your needs.
remote_theme: pmarsceill/just-the-docs
aux_links:
  "View on GitHub":
    - "//github.com/intersystems-community/iris-driver-distribution"
## theme: jekyll-theme-minimal

# social links
twitter_username: intersystems # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
